name: norka
version: git
title: Norka
summary: Text editor baked for simplicity.
description: |
  Imagine text writing experience without the hassle. Don't worry about saving files, complex markup, or accidentally deleted notes.
  Do what you want to do - concentrate on beautiful stories, short notes, or documenting. Norka cares about you.
  - All your notes inside
  - Automatically saved in place
  - Can be easily exported to files in one click
  - If you neet markup - use markdown
  - Don't like the default theme - choose different

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  snapcraft-preload:
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    build-packages:
      - gcc-multilib
      - g++-multilib
  elementary-theme:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/elementary/stylesheet.git
    build-packages:
      - sassc
  elementary-icons:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/elementary/icons.git
    build-packages:
      - x11-apps
      - librsvg2-bin
  elementary-sdk:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: 'true'
    override-build: |
      sudo apt -y install software-properties-common
      sudo add-apt-repository -y ppa:elementary-os/stable
      sudo apt -y update
      sudo apt -y upgrade
  pip:
    plugin: python
    python-version: python3
    python-packages:
      - writeasapi
      - mistune==2.0.0a4
      - requests
  norka:
    plugin: meson
    meson-parameters: [--prefix=/snap/norka/current/usr]
    source: https://github.com/TenderOwl/Norka.git
    build-packages:
      - gettext
      - libgtk-3-dev
      - libgranite-dev
      - libglib2.0-dev
      - libgtkspell3-3-dev
      - libgtksourceview-3.0-dev
    stage-packages:
      - libgranite5
      - python3
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-3.0
      - gir1.2-gtkspell3-3.0
      - gir1.2-gtksource-3.0
      - gir1.2-granite-1.0
    override-pull: |
      snapcraftctl pull
      patch -p1 < build-aux/elementary-theme.patch
      sed -i.bak -e 's|Icon=@icon@|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.tenderowl.norka.svg|' data/com.github.tenderowl.norka.desktop.in.in
    # override-build: |
    #   snapcraftctl build
    organize:
      snap/norka/current/usr: usr
    after:
      - elementary-sdk
      - elementary-icons
      - elementary-theme
      - pip
    parse-info: [usr/share/metainfo/com.github.tenderowl.norka.appdata.xml]

apps:
  norka:
    command: desktop-launch snapcraft-preload $SNAP/usr/bin/com.github.tenderowl.norka
    desktop: usr/share/applications/com.github.tenderowl.norka.desktop
    extensions: [gnome-3-34]
    plugs:
      - desktop
      - gsettings
      - wayland
      - x11
      - home
      - network
      - hostname-control
      - mount-observe
      - login-session-observe
    slots:
      - dbus-norka
    common-id: com.github.tenderowl.norka
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GTK_USE_PORTAL: "1"

slots:
  dbus-norka:
    interface: dbus
    bus: session
    name: com.github.tenderowl.norka
